name: CI
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Nim
        uses: nim-lang/setup-nim-action@v2
        with:
          nim-version: "2.2.x"
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: nimble setup -y

      - name: Unit tests
        run: nimble test

      - name: Integration tests
        run: nimble testIntegration
